version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./docker/mongodb/data:/data/db
  postgres-orders:
    image: postgres:latest
    container_name: postgres-orders
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_service
    volumes:
      - ./docker/pg/pg_orders/data:/var/lib/postgresql/data
      - ./docker/pg/pg_orders/init_orders.sql:/docker-entrypoint-initdb.d/init_orders.sql
  postgres-inventories:
    image: postgres:latest
    container_name: postgres-inventories
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_service
    volumes:
      - ./docker/pg/pg_inventories/data:/var/lib/postgresql/data
      - ./docker/pg/pg_inventories/init_inventories.sql:/docker-entrypoint-initdb.d/init_inventories.sql