spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/inventory_service?currentSchema=dev
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      pool-name: HikariCP
  jpa:
    properties:
      hibernate:
        default_schema: dev
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations:
      - classpath:db/migration/structure
      - classpath:db/migration/data
    validate-on-migrate: true
    schemas:
      - dev
    default-schema: dev

server:
  port: 8082
